fix: handle function toString node10 change
In node 10 the space preceding with () is removed.

This causes the error:

      TypeError: Cannot read properties of null (reading '1')